[modules]
autoload=yes
load => res_ari.so
load => res_ari_channels.so
load => res_ari_bridges.so
load => res_ari_events.so
load => res_pjsip.so
load => res_pjsip_authenticator_digest.so
load => res_pjsip_endpoint_identifier_ip.so
load => chan_pjsip.so